### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by zanjs** [fullstackio/yelp-clone#1]
## npm start error

```
ERROR in ./src/app.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory 
```
## full

```
➜  yelp-clone git:(master) npm start

> yelp@1.0.0 start /Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone
> NODE_ENV=development ./node_modules/.bin/hjs-dev-server

Listening at http://localhost:3000
webpack built 53e2002c7dadc387ad7f in 427ms
Hash: 53e2002c7dadc387ad7f
Version: webpack 1.13.1
Time: 427ms
 Asset    Size  Chunks       Chunk Names
app.js  208 kB       0       main
chunk    {0} app.js (main) 73.1 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js 4.18 kB {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] ./~/strip-ansi/index.js 161 bytes {0} [built]
    [4] ./~/ansi-regex/index.js 135 bytes {0} [built]
    [5] (webpack)-hot-middleware/client-overlay.js 1.73 kB {0} [built]
    [6] ./~/ansi-html/index.js 4.02 kB {0} [built]
    [7] ./~/html-entities/index.js 231 bytes {0} [built]
    [8] ./~/html-entities/lib/xml-entities.js 2.98 kB {0} [built]
    [9] ./~/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
   [10] ./~/html-entities/lib/html5-entities.js 49 kB {0} [built]
   [11] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]

ERROR in ./src/app.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone"
    at /Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.addConfig (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/julaud/www/Frontend/javascript/react/reactjs/yelp-clone/node_modules/babel-core/lib/transformation/file/index.js:140:24)
 @ multi main
```

**Comment by zanjs** [comment]
`npm install --save-dev babel-preset-stage-0`
